from gym.envs.registration import register

# low level control tasks
register(
    id='Hover-v0',
    entry_point='gym_aero.envs:HoverEnv',
)
register(
    id='RandomWaypoint-v0',
    entry_point='gym_aero.envs:RandomWaypointEnv',
)
register(
    id='Land-v0',
    entry_point='gym_aero.envs:LandEnv',
)
register(
    id='TargetFollow-v0',
    entry_point='gym_aero.envs:TargetFollowEnv',
)
register(
    id='Trajectory-v0',
    entry_point='gym_aero.envs:TrajectoryEnv',
)
register(
    id='Recovery-v0',
    entry_point='gym_aero.envs:RecoveryEnv',
)
register(
    id='Perch-v0',
    entry_point='gym_aero.envs:PerchEnv',
)
register(
    id='PathFollow-v0',
    entry_point='gym_aero.envs:PathFollowEnv',
)

# hierarchical tasks
register(
    id='BoxWorld-v0',
    entry_point='gym_aero.h_envs:BoxWorld',
)
register(
    id='PlannerBox-v0',
    entry_point='gym_aero.h_envs:PlannerBoxEnv',
)
register(
    id='Planner-v0',
    entry_point='gym_aero.h_envs:PlannerEnv',
)
register(
    id='TrajectoryTerm-v0',
    entry_point='gym_aero.h_envs:TermTrajectoryEnv',
)
register(
    id='RandomWaypointTerm-v0',
    entry_point='gym_aero.h_envs:RandomWaypointEnvTerm',
)
register(
    id='TrajectorySplineTerm-v0',
    entry_point='gym_aero.h_envs:TrajectoryEnvSplineTerm',
)

# multi-task environments
register(
    id='HoverMT-v0',
    entry_point='gym_aero.mt_envs:HoverMTEnv',
)
register(
    id='StaticWaypointMT-v0',
    entry_point='gym_aero.mt_envs:StaticWaypointMTEnv',
)
register(
    id='RandomWaypointMT-v0',
    entry_point='gym_aero.mt_envs:RandomWaypointMTEnv',
)
register(
    id='LandMT-v0',
    entry_point='gym_aero.mt_envs:LandMTEnv',
)
register(
    id='PerchMT-v0',
    entry_point='gym_aero.mt_envs:PerchMTEnv',
)

register(
    id='One-v0',
    entry_point='gym_aero.mt_envs:OneEnv',
)
register(
    id='Two-v0',
    entry_point='gym_aero.mt_envs:TwoEnv',
)
register(
    id='Three-v0',
    entry_point='gym_aero.mt_envs:ThreeEnv',
)